### ISSUE TITLE
CN21 Cam

### ISSUE THREAD

**Issue by ssombra** [alienatedsec/yi-hack-v5#146]
I have an old Yi Cam, I believe its one of the firsts batch and I havent used it for a while because I just cant connect it to the app anuymore (I believe it is because it is intended for China only). I opened it and I see it has a Hi3158 chip inside. Does this firmware work for my camera? I don't care about using it with the app, I am ok with just being able to see a stream (from VLC for instance)

**Comment by alienatedsec** [comment]
@ssombra there was a problem with proxychain in general, especially with early versions of `yi-hack-v5`. I got it fixed with [this `0.4.0b` release](https://github.com/alienatedsec/yi-hack-v5/releases/tag/0.4.0b). Please, if you wish to try again, this would be great. If you meant `Hi3518` chipset, it should work - make sure you load the right baseline firmware.
