### ISSUE TITLE
Yi Outdoor 1080p error Snapshot and Home Assistant 

### ISSUE THREAD

**Issue by Miguelin96** [alienatedsec/yi-hack-v5#223]
I installed hack v5 in Yi Outdoor but it takes time to load the web and the screenshots, in addition to the interaction with home assist, it does not work correctly, it causes the camera to stay blocked, from the Yi App everything is correct.

![image](https://user-images.githubusercontent.com/54648539/210345209-4f9a80fc-9983-4d6c-ab48-47afe236e320.png)

**Comment by alienatedsec** [comment]
Sorry, I just introduced a template. Please fill the below:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Set Up Details (please complete the following information):**
 - Firmware Version: [e.g. 0.3.7]
 - Device: [e.g., YI HOME 1080P]
 - Model: [e.g., 48US]

**Additional context**
Add any other context about the problem here. If any other systems are involved, please complete the following:
 - Name of the system [e.g., Home Assistant]
 - Version [e.g., 2022-12-xx]

**Technical Details**
Please add any technical details (e.g., log files)
